### ISSUE TITLE
Scry not returning any results

### ISSUE THREAD

**Issue by darth-rufus** [dbeniamine/vizardry#2] opened 2015-11-11 16:36 UTC
I have been running several queries with the vizardry plugin and I am not getting any results.  Here is what I am typing in Vim:

:Scry vizardry

which returns

Searching for vizardry...
(actual query: 'vizardry+vim+fork:true')
No results found for query 'vizardry'
Press ENTER or type command to continue

Am I missing any setup or is there a bug running the queries on Linux?

Invoke and Evolve seem to be behaving as I would expect.

++alan

**Comment by dbeniamine** [comment] 2015-11-11 17:49
Hello,

This is weird, Invoke and Scry uses the same functions to connect to github.

Invoke works fine if you do something like `:Invoke someplugin` where `someplugin` is not installed locally ?

Do you use a proxy on your machine ?

I just pushed some modification to debug Vizardry, can you do:

    :Evolve vizardry
    :let g:VizardryDebug=1
    :Scry vizardry

and copy the output here ?

I don't think that the  bug come from Linux as I'm working on Linux.

David

**Comment by darth-rufus** [comment] 2015-11-11 20:48
David,

Looks like i misspoke (or mistyped) but it looks like Invoke is also not working on my box (running latest Arch Linux).  I get the same error when trying to Invoke a non-installed plugin.  curl is installed as well as atool (which as I recall are the only dependencies other than Vim).

Proxy is a no.

Re-ran the Evolve vizardry and it worked fine.  Restarted vim and here's what i get:
Searching for vizardry...
(actual query: 'vizardry+vim+fork:true')
zsh:1: no matches found: https://api.github.com/search/repositories?q=vizardry+vim+fork:true
[]
[]
No results found for query 'vizardry'
Press ENTER or type command to continue

Looks like zsh may be a problem.  I had a problem with a couple of other command line tools like youtube-dl that kicked out a similar error.  Enclosing the URL in double quotes seemed to resolve the symptom.

I hope that this helps and SUPER KUDOS on a way cool forked-plugin :).

++alan

**Comment by darth-rufus** [comment] 2015-11-11 20:54
David,

Here's a follow up.  I changed my shell to bash and it works fine.  When I changed back to zsh, I got the same debug message as last time.

++alan

**Comment by dbeniamine** [comment] 2015-11-11 21:27
Thanks for your input.

I'll do some test on zsh on my machine.

For informations atool is only needed if you have installed scripts from vim.org and want to evolve them, otherwise I only need curl installed.

**Comment by dbeniamine** [comment] 2015-11-11 22:14
So I'm not able to reproduce the bug on zsh, maybe something on your zshrc / how do you launch vim ?

Still I've protected every urls with `'url'` tell me if it helps ...

**Comment by darth-rufus** [comment] 2015-11-11 22:24
David,

It could be the zsh profile configuration tool that I am using (oh-my-zsh).  In any event, I applied the patch and now all seems to be well.  I can use Invoke and Scry without any problems.  Thanks for your help.

Thanks for the feedback on atool as well.

++alan

**Comment by dbeniamine** [comment] 2015-11-12 08:25
Alan,

My test was wrong, the system call in vim didn't fall bach to zsh but bash that why I didn't manage to reproduce the bug.
I've seen an other url not sanitize, I've cleaned it everything seems to work on zsh, I close the issue for now. Tell me  if you find some other bugs.

David

**Closed by dbeniamine** 2015-11-12 08:25 UTC
Labels: bug

**Comment by darth-rufus** [comment] 2015-11-12 15:31
Thanks, David.  Keep up the good work.  If I run into anything else I will let you know.

++alan
